use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/seeEmil/SeeEmilRepo.git'

platform :ios, '9.0'

target 'SEPhotoPuzzle_Example' do
  pod 'SEPhotoPuzzle', :path => '../'
  pod 'SEPhotoAlbum'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '5.0'
                config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'        
        end
    end
end